/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import EDD.ArbolB;
import EDD.arbolAVL;
import EDD.tablaHash;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author byron
 */
public class Inicio extends javax.swing.JFrame {
  /**
     * Creates new form Inicio
     */
    public static Clases_Estaticas clases= new Clases_Estaticas();
    public Inicio() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        //System.out.println(datos.contains("el"));
        /*clases.bTree.insertar(new Libro(10, "Lea", "Ssombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(20, "wLa", "Sombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(30, "La", "Somsbra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(40, "Lna", "Sombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(50, "Lsa", "Sombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(90, "Lsa", "Sombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(13, "Laa", "Socmbra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(65, "Laa", "Sombsra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(56, "aLa", "Soasmbra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(1, "La", "Socmbra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(91, "La", "Sombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(9, "Lsa", "Sombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
       clases. bTree.insertar(new Libro(7, "Lza", "Sombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(901, "Laa", "Sombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(568, "Lza", "Sombra", "De", "Gray", "Unica", "Tozdas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(97, "Lza", "Sombra", "De", "Gray", "Unica", "Txodas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(17, "Lva", "Sombra", "De", "Gray", "Unica", "Txodas", "Ingles", "13264"));
        clases.bTree.insertar(new Libro(10, "Lxa", "Sombra", "De", "Gray", "Unica", "Todas", "Ingles", "13264"));
        clases.bTree.imprimirNodo();
        clases.arbolito.insertar("azul", clases.bTree);
        clases.arbolito.insertar("amarillo", clases.bTree);
        clases.arbolito.insertar("dato", clases.bTree);
        clases.arbolito.insertar("anaranjado", clases.bTree);
        clases.arbolito.insertar("zoor", clases.bTree);
        clases.arbolito.colocarGrafo();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Inicio Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar Usuarios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Password");

        jLabel2.setText("Carnet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(user))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(user.getText().equals("") || pass.getText().equals("")){
    JOptionPane.showMessageDialog(null, "No hay datos suficientes");
}else{
    try {
        boolean bandera= clases.tablita.buscarCredenciales(user.getText(), pass.getText());
        if(bandera){
            clases.user=clases.tablita.modificarDatos(user.getText(), pass.getText());
            this.setVisible(false);
            new Menu().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No hay Usuario valido");
        }
    } catch (Exception ex) {
        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
new Usuarios().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    
                    
                    
                    new Inicio().setVisible(true);
                    
                    
                    
                } catch (Exception ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
